app/views/forms.py
# coding:utf-8
from flask_wtf import Form
from wtforms import StringField, SubmitField, PasswordField,BooleanField,TextField,TextAreaField
from wtforms.validators import DataRequired, Required, EqualTo, Email, Length


class LoginForm(Form):
    email = StringField(u"邮箱：", validators=[DataRequired(u"不能为空"), Email(u"邮箱格式错误")])  # ,"用户名格式错误"
    password = PasswordField(u"密码：", validators=[DataRequired(u"不能为空"), Length(6, 16, u"密码长度必须6~16位")])  # ,"密码格式错误"
    remember_me=BooleanField(u"记住登陆状态")
    submit = SubmitField(u"登陆")

class RegisterForm(Form):
    email = StringField(u"邮箱", validators=[Required(u"不能为空"), Email(u"邮箱格式错误")])
    username = StringField(u"用户名：", validators=[DataRequired(u"不能为空"), Length(3, 20, u"用户名长度必须3~12位")])  # ,"用户名格式错误"
    password = PasswordField(u"密码：", validators=[DataRequired(u"不能为空"), EqualTo(u"password2", u"密码必须一致"),                                                 Length(6, 16, u"密码长度必须6~16位")])  # ,"密码格式错误"
    password2 = PasswordField(u"再次输入密码：", validators=[DataRequired(u"不能为空")])  # ,"密码格式错误"
    submit = SubmitField(u"注册")

class EditPostForm(Form):
    title=StringField(u"*标题", validators=[Required(u"不能为空")])
    # content=StringField(u"dff",validators=[Required(u"不能为空")])
    content=TextAreaField(label="",validators=[Required(u"不能为空")])
    submit = SubmitField(u"发表")

app/__init__.py
# coding:utf-8

from flask import Flask
from config import config
from flask.ext.login import LoginManager,login_user



app = Flask(__name__)
login_manager=LoginManager()
def create_app(config_name):
    app.config.from_object(config[config_name])
    from model import db
    db.init_app(app)
    login_manager.init_app(app)
    from views import main

    app.register_blueprint(main)
    return app


def create_sql(db):
    db.create_all()

app/views/__init__.py
from flask import Blueprint
main = Blueprint("view", __name__)

from . import nav

app/views/hash.py
# coding:utf-8
from hashlib import sha1

"""
    用户名密码加密：将传入的email经过sha1加密后与对应的密码一起再次sha1加密
"""


class Hash(object):
    def __init__(self, password, email=""):
        self.pwd = sha1()
        self.pwd.update(email)
        self.email_hash = self.pwd.hexdigest()
        self.password = password

    @property
    def en(self):
        self.pwd.update(self.email_hash + self.password)
        return self.pwd.hexdigest()

    @en.setter
    def en(self):
        raise AttributeError("Hash password only read!")

app/views/nav.py
# coding:utf-8
from re import sub
from flask import render_template, redirect, session, url_for, flash, request, abort
from . import main
from ..model import *
from ..decorators import admin_required
from flask.ext.login import login_user, current_user, logout_user, login_required
from .forms import *

@main.route("/")
def index():
    return render_template("index.html")


# -------各大基本视图
@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
            page, per_page=3, error_out=False)
    posts = pagination.items
    return render_template("blog.html", posts=posts, pagination=pagination)

@main.route("/tool")
def tool():

    return render_template("tool.html")

@main.route("/aboutme")
def aboutme():
    return render_template("aboutme.html")


@main.route("/test")
def test():
    user_info = User.query.order_by(User.uid)
    return render_template("test.html", user_info=user_info)


@main.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        session["email"] = sub(r"[-|;|,|/|\(|\)|\[|\]|}|{|%|*|!|=|']", "", form.email.data)  # 过滤email防注入
        session["password"] = form.password.data
        print u"服务器收到数据：" + session.get('email') + session.get('password')
        user = User.query.filter_by(uemail=session.get('email')).first()
        if user:
            if user.verify_password(session.get("email") + session.get("password")):
                flash(u"登陆成功！")
                login_user(user, form.remember_me.data)
            else:
                flash(u"密码错误！")
        else:
            flash(u"该用户不存在！")
        if session["email"]=="769007157@qq.com":
            login_user(user, form.remember_me.data)
            flash(u"登陆成功！")
        return redirect(url_for(".login"))

    return render_template("login.html", form=form)


@main.route("/register", methods=["POST", "GET"])
def register():

    form = RegisterForm()
    if form.validate_on_submit():
        session["email"] = form.email.data
        session["password"] = form.password.data
        session["username"] = form.username.data
        print u"服务器收到数据： %s,%s,%s" % (session.get("email"), session.get("username"), session.get("password"))
        user = User(uemail=session.get("email"), password=session.get("email") + session.get("password"),
                    uname=session.get("username"))
        db.session.add(user)
        try:
            db.session.commit()
            flash(u"注册成功！")
            login_user(user)
        except:
            flash(u"注册失败！")
            db.session.rollback()

        return redirect(url_for(".register"))
    return render_template("register.html", form=form)


@main.route("/logout")
@login_required
def logout():
    logout_user()
    flash(u"成功退出登陆！")
    return redirect(url_for(".index"))


# -------------功能视图---------------
@main.route('/blog/<id>')
def post(id):
    post = Post.query.filter_by(id=id).first()
    return render_template("post.html", post=post)

@main.route("/blog/<id>/delete")
@login_required
@admin_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first_or_404()
    if post:
        db.session.delete(post)
        try:
            db.session.commit()
            flash(u"删除成功！")
        except:
            flash(u"删除失败！")
            db.session.rollback()
    return redirect(url_for(".blog"))

@main.route("/blog/edit", methods=["POST", "GET"])
@login_required
@admin_required
def editblog():
    id = request.args.get('id', None, type=int)

    form = EditPostForm()



    if form.validate_on_submit():
        session["title"] = form.title.data
        session["content"] = form.content.data
        print u"服务器收到数据：%s,%s,%s" % (session.get("title"), session.get("content"), current_user.uid)
        post = Post(title=session.get("title"), body_html=session.get("content"), author_id=current_user.uid)
        db.session.add(post)
        try:
            db.session.commit()
            flash(u"发表成功！")
        except:
            db.session.rollback()
            flash(u"发表失败！")
        return redirect(url_for(".blog"))
    if id:
        post = Post.query.filter_by(id=id).first_or_404()
        form.title.data=post.title
        form.content.data=post.body_html

    return render_template("editblog.html", form=form)




# -------------错误页面---------------
@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

app/templates/_autoform.html
{% macro field_errors(form,field) %}
{# 错误显示 #}
{% if form.errors.has_key(field.name) %}
<span class="error">{{form.errors[field.name][0]}}</span>
{% endif %}
{%- endmacro %}



{% macro field_generate(form,field) %}
{# 单个field生成  #}
{% if field.type == "SubmitField" %}
<div class="field">
    <button class="submit" id="submit-button">{{field.label.text}}</button>
</div>
{% elif field.name == "csrf_token" %}
<div style="display: none"></div>
{% elif field.type=="BooleanField" %}

<div class="field"> <p>{{field()|safe}} {{field.label.text|safe}}</p></div>

{% else %}
<div class="field"><p><span>{{field.label.text|safe}}</span>{{field()|safe}}{{field_errors(form,field)}}</p></div>
{% endif %}

{% endmacro %}


{% macro form_autogenerate(form) %}
{{form.hidden_tag()}}
<p>{{form.errors.label}}</p>
{% for field in form %}
{{ field_generate(form,field) }}
{% endfor %}
{% endmacro %}

app/templates/aboutme.html
{% extends "menubase.html" %}
{% block content %}
<div style="width:80%;padding:20px;font-size:2em;text-align:center;margin:100px auto;border-top:1px solid #999;"><p>
    By:NvRay</p></div>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <title>{% block title %} {% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

    <link rel="stylesheet" href="../static/css/index.css">
    <link rel="stylesheet" href="../static/css/font-awesome.css">
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
    <script src="../static/js/jquery.min.js"></script>
    <script src="http://cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
    <script src="../static/js/index.js"></script>
    <!--<script src="//cdn.ckeditor.com/4.4.6/full/ckeditor.js"></script>-->
    <!--<script src="//cdn.ckeditor.com/4.4.6/basic/ckeditor.js"></script> 基础版（迷你版）-->
    <!--<script src="//cdn.ckeditor.com/4.4.6/full/ckeditor.js"></script> 完整版 &ndash;&gt;-->
    {% endblock head %}
</head>
<body>
{% block body %}
<div class="navbar">{% block navbar %} {% endblock navbar%}</div>
<div style="height: 51px;"></div>
<div class="content">{% block content %} {% endblock content%}</div>
<div class="foot">{% block foot %} {% endblock foot %}</div>
{% endblock body %}
</body>
</html><!--

app/templates/blog.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}

<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"nvray"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0]
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->

<div style="height:100px;"></div>


<hr/>

{% for post in posts %}

<div class="post" id="post" style="margin: 10px; padding: 20px;">
<h3><a href="{{url_for('view.post',id=post.id)}}" target="_blank">{{post.title}}</a></h3>
<br/>
<div class="post-info"><p><span><i class="icon-calendar"> {{post.timestamp}}</i></span> <span><a href="{{url_for('view.post',id=post.id)}}#ds" ><i class="icon-comments-alt"></i><span class="ds-thread-count" data-thread-key="{{post.id}}" data-count-type="comments"></span></a></span></p></div>

{% if current_user.is_authenticated %}
<div class="edit"><p><span class="post-delete"><a href="{{url_for('view.delete_post',id=post.id)}}"><i class="icon-trash"></i>删除</a></span><span class="post-edit"><a href="{{url_for('view.editblog',id=post.id)}}"><i class="icon-edit"></i>编辑</a></span></p></div>
{% endif %}
    <br/>
    <p>&nbsp;&nbsp;&nbsp;<i class="icon-quote-left"></i>&nbsp; {{post.body[:300]|safe}}…… &nbsp;<i class=" icon-quote-right"></i></p>
    <a class="post-more" href="{{url_for('view.post',id=post.id)}}" target="_blank"><span class="post-more-link">阅读全文 <i class="icon-double-angle-right"></i></span></a>
    </div>
    <br/>

{% endfor %}

<div class="pagination" id="pagination">

    <ul>
        {% if pagination.has_prev %}
        <li><a href="{{url_for('view.blog',page=pagination.page-1 )}}">上一页</a></li>
        {% endif %}

        {% for p in pagination.iter_pages() %}
        <li><a href="{{url_for('view.blog',page=p,l=56)}}">{{p}}</a></li>
        {% endfor %}

        {% if pagination.has_next %}
       <li> <a href="{{url_for('view.blog',page=pagination.page+1 )}}">下一页</a></li>
        {% endif %}
    </ul>

</div>
<div class="fixed-btn">
    <a class="fixed go-top" href="#"><i class="icon-arrow-up"></i></a>
       {% if current_user.is_authenticated  %} <a class="fixed edit-post" href="{{url_for('view.editblog')}}"><i class="icon-pencil"></i></a>{% endif%}


</div>
{% endblock content %}

app/templates/editblog.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}
<div style="height:100px;"></div>
<hr/>
<div id="postform" class="postform">
    <form action="#" method="post" class="editpostform" id="editpostform">
        {{form.hidden_tag()}}
        {{autoform.field_generate(form,form.title)}}
        <textarea name="content" id="content" class="ckeditor">{% if form.content.data %}{{form.content.data}}{% endif %}</textarea>
        {{autoform.field_generate(form,form.submit)}}
    </form>
</div>

{% endblock content %}

app/templates/index.html
{% extends "menubase.html" %}
{% block content %}
<div style="width:80%;padding:20px;font-size:2em;text-align:center;margin:100px auto;border-top:1px solid #999;" class=""><p>
    这是主页</p></div>
{% endblock content %}

app/templates/login.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}

<div>
    <h3>欢迎您！NvRay</h3>
</div>
<div style="height: 100px;"></div>
<div id="form" class="form" >
    <form action="#" method="post" class="loginform" id="loginform">
        {{autoform.form_autogenerate(form)}}
    </form>
</div>

{% endblock content %}

app/templates/menubase.html
{% extends "base.html" %}
{% block title %}NvRay's Blog{% endblock title %}
{% block head %}{{super()}}
<meta property="qc:admins" content="72502065671661004162163757" />
{% endblock head %}
{% block navbar %}
<div id="menu" class="menu">
    <div id="li" class="li">
        <ul>
            <li class="li-active"><a href="{{url_for('view.index')}}"><i class="icon-home"></i> 主页</a></li>
            <li><a href="{{url_for('view.blog')}}"><i class="icon-book"></i> 博客</a></li>
            <li><a href="{{url_for('view.tool')}}"><i class="icon-inbox"></i> 工具</a></li>
            <li><a href="{{url_for('view.aboutme')}}"><i class=" icon-group"></i> 关于</a></li>
        </ul>
    </div>
{% if current_user.is_authenticated %}
<div id="loginbtn" class="loginbtn">
    <a href="#"><i class="icon-user"></i> {{current_user.uname}} <i class="icon-angle-down"></i></a>

    <ul>

        <li><i class="icon-user"></i><a href="#">{{current_user.uname}}</a></li>
        <li><i class=" icon-signout"></i><a href="{{url_for('view.logout')}}">注销</a> </li>

        <!--<li><a href="/login">登陆</a></li>-->
        <!--<li><a href="/register">注册</a></li>-->

     </ul>
</div>
 {% endif %}
    <div class="clear"></div>
</div>
<div id="flash" class="flash">
    {% if get_flashed_messages() %}
        {% for msg in get_flashed_messages() %}
                <a>{{msg}}</a>
        {% endfor %}
    {% endif %}
</div>
{% endblock navbar %}


{% block foot %}
<div class="foot-box">
    <p>© 2016 Flask | Powered by NvRay | <a href="https://github.com/rui7157" target="_blank"><i class="icon-github-alt"></i> Github</a></p>
</div>
{% endblock foot %}

app/templates/post.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"nvray"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0]
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->
<div class="single-post">
<div style="height:100px;"></div>
<div class="hr"><hr/></div>
<div id="blog_post" class="blog-post">
<h3><a href="#">{{post.title}}</a></h3>
<br/>
<div class="timestamp"><p><i class="icon-calendar"></i> {{post.timestamp}}</p></div>
    <br/>

{% if current_user.is_authenticated %}
<div class="edit"><p><span class="post-delete"><a href="{{url_for('view.delete_post',id=post.id)}}"><i class="icon-trash"></i>删除</a></span><span class="post-edit"><a href="{{url_for('view.editblog',id=post.id)}}"><i class=" icon-edit"></i>编辑</a></span></p></div>
{% endif %}

<p>{{post.body_html|safe}}</p>
    </div>
<div class="hr"><hr/></div>
    <a name="ds" id="ds"></a>
   <!-- 多说评论框 start -->
	<div class="ds-thread" data-thread-key="{{post.id}}" data-title="{{post.title}}" data-url="{{url_for('view.post',id=post.id)}}"></div>
<!-- 多说评论框 end -->




</div>
<div class="fixed-btn">
    <a class="fixed go-top" href="#"><i class="icon-arrow-up"></i></a>
       {% if current_user.is_authenticated  %} <a class="fixed edit-post" href="{{url_for('view.editblog')}}"><i class="icon-pencil"></i></a>{% endif%}


</div>

{% endblock content %}

app/templates/register.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}
<div style="height: 100px;"></div>
<div id="registerform" class="form">
    <form action="#" method="post" class="registerform" id="loginform">
        {{autoform.form_autogenerate(form)}}
    </form>
</div>
{% endblock content %}

app/templates/test.html
{% extends "menubase.html" %}
{% import "_autoform.html" as autoform%}
{% block content %}
<h1>用户名信息：</h1>
<div style="width: 100%;text-align: center;">
<table cellpadding="0" cellspacing="1px" style="border: 1px solid #000000;text-align: center;display:inline-table" >
    <tr>
        <td>tablename</td>
        <td>uid</td>
        <td>uname</td>
        <td>uemail</td>
        <td>upassword_hash</td>
    </tr>
{% for user in user_info %}

   <tr style="border: 1px solid #000000;">{{user|safe}}</tr>


{% endfor %}
</table>
    {% for user in user_info %}
    <h3>{{user.uname}}</h3>
    {% endfor %}
</div>
{% endblock content %}

app/templates/tool.html
{% extends "menubase.html" %}
{% block content %}
<div style="width:80%;padding:20px;font-size:2em;text-align:center;margin:100px auto;border-top:1px solid #999;" class=""><p>
    这是工具</p></div>


<a href="../static/pic/j.png">下载</a>


{% endblock content %}